### ISSUE TITLE
404 Not Found Error when Deleting CustomObject from UnresolvedReferencesService

### ISSUE THREAD

**Issue by andihalberkamp** [commercetools/commercetools-project-sync#619]
hi

**Comment by lojzatran** [comment]
Hi Andi :)

Thank you for reporting the issue.

I will have a look at it and see what I can do do.

Best,
Lam

**Comment by andihalberkamp** [comment]
thanks Lam, looking forward to your answer

**Comment by lojzatran** [comment]
Hi Andi,

I created a PR that should fix this issue: https://github.com/commercetools/commercetools-sync-java/pull/1210

**Comment by andihalberkamp** [comment]
Perfekt thanks a lot

**Comment by andihalberkamp** [comment]
hi Lam,

When will this fix be released?

Best
Andi

**Comment by lojzatran** [comment]
Hi Andi,

Sorry I‘m not responsible for this repo anymore. I guess someone else will have to look at your issue now.

Best,
Lam

**Comment by andihalberkamp** [comment]
Hi @jenschude ,

thank you for fixing the issue and providing the new release version '5.5.1', but unfortunately, the same issue still persists within this version.This Is a error which I got today within the version 5.5.1:: 
```

"i.v.r.b.c.e.NotFoundException: detailMessage: Client error response [url] https://api.europe-west1.gcp.commercetools.com/carhartt-preproduction/custom-objects/commercetools-sync-java.UnresolvedReferencesService.productDrafts/1b40a6797c7a1a0378e77fca087a33f7e000147b [status code] 404 [reason phrase] Not Found
summary: DELETE https://api.europe-west1.gcp.commercetools.com/carhartt-preproduction/custom-objects/commercetools-sync-java.UnresolvedReferencesService.productDrafts/1b40a6797c7a1a0378e77fca087a33f7e000147b failed  with response code 404 with X-Correlation-ID `{key=x-correlation-id, value=carhartt-preproduction/56d18e87-1067-4a29-838c-33b30215d9f4}` on 2025-04-05T09:18:54.881772Z
http response formatted body: {
  "statusCode" : 404,
  "message" : "The CustomObject with ID '(commercetools-sync-java.UnresolvedReferencesService.productDrafts,1b40a6797c7a1a0378e77fca087a33f7e000147b)' was not found.",
  "errors" : [ {
    "code" : "ResourceNotFound",
    "message" : "The CustomObject with ID '(commercetools-sync-java.UnresolvedReferencesService.productDrafts,1b40a6797c7a1a0378e77fca087a33f7e000147b)' was not found."
  } ]
}
http response: io.vrap.rmf.base.client.ApiHttpResponse@6e
```
Please check why the issue still occurs.

best Andi
